apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana-app-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: banana-app
  template:
    metadata:
      labels:
        app: banana-app
    spec:      
      containers:
      - image: hashicorp/http-echo
        args:
          - "-text=banana"
          - "-listen=:32333"
        name: banana-app
        imagePullPolicy: Always
        ports:
        - containerPort: 32333
          hostPort: 32333
        resources:
          limits:
            ephemeral-storage: 512Mi
          requests:
            ephemeral-storage: 512Mi
---
kind: Service
apiVersion: v1

metadata:
  name: banana-elb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer
  selector:
    app: banana-app
  ports:
    - name: http
      port: 32333
      targetPort: 32333
