# {{ model_name }} dataset
# Train command: python train.py --data {{ model_name }}.yaml
# Default dataset location is next to /yolov5:
#   /parent_folder
#     /{{ model_name }}
#     /yolov5


# download command/URL (optional)
# download: 

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ../{{ model_name }}/images/train/
val: ../{{ model_name }}/images/valid/

# number of classes
nc: {{ num_classes }}

# class names
names: {{ class_list }}
