apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmet-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helmet-app
  template:
    metadata:
      labels:
        app: helmet-app
    spec:      
      containers:
      - env:
        - name: DB_HOSTNAME
          value: {{$.rds_address.value}}
        - name: DB_USERNAME
          value: {{$.db_username.value}}
        - name: DB_PASSWORD
          value: {{$.db_password.value}}
        image: justatoaster64/yolov5-helmet-detector:latest
        name: helmet-app
        imagePullPolicy: Always
        ports:
          - containerPort: 32332
            hostPort: 32332
        resources:
          limits:
            ephemeral-storage: 512Mi
          requests:
            ephemeral-storage: 512Mi
---
kind: Service
apiVersion: v1

metadata:
  name: helmet-elb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer
  selector:
    app: helmet-app
  ports:
    - name: http
      port: 32332
      targetPort: 32332
