apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmet-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helmet-app
  template:
    metadata:
      labels:
        app: helmet-app
    spec:      
      containers:
      - env:
        - name: DB_HOSTNAME
          value: {{$.rds_address.value}}
        - name: DB_USERNAME
          value: {{$.db_username.value}}
        - name: DB_PASSWORD
          value: {{$.db_password.value}}
        image: justatoaster64/yolov5-helmet-detector:latest
        name: helmet-app
        imagePullPolicy: Always
        ports:
          - containerPort: 32332
            hostPort: 32332
        resources:
          limits:
            ephemeral-storage: 512Mi
          requests:
            ephemeral-storage: 512Mi
---

kind: Service
apiVersion: v1
metadata:
  name: helmet-service
spec:
  selector:
    app: helmet-app
  type: NodePort
  ports:
    - port: 32332
      nodePort: 32332

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helmet-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
        paths:
          - path: /helmet
            pathType: Prefix
            backend:
              service:
                name: helmet-service
                port: 
                  number: 32332
