apiVersion: apps/v1
kind: Deployment
metadata:
  name: labeling-app-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: labeling-app
  template:
    metadata:
      labels:
        app: labeling-app
    spec:      
      containers:
      - env:
        - name: DB_HOSTNAME
          value: "{{$.rds_address.value}}"
        - name: DB_USERNAME
          value: "{{$.db_username.value}}"
        - name: DB_PASSWORD
          value: "{{$.db_password.value}}"
        - name: AWS_DEFAULT_REGION
          value: "{{$.region.value}}"
        - name: MODELS_BUCKET
          value: "{{$.models_bucket.value}}"
        - name: MIN_TRAINING_SET_SIZE
          value: "{{$.min_training_data.value}}"
        - name: MIN_VALIDATION_SET_SIZE
          value: "{{$.min_validation_data.value}}"
        image: justatoaster64/yolov5-labeling-detection-webservice:latest
        name: labeling-app
        imagePullPolicy: Always
        ports:
          - containerPort: 32332
            hostPort: 32332
        resources:
          limits:
            ephemeral-storage: 512Mi
          requests:
            ephemeral-storage: 512Mi
---
kind: Service
apiVersion: v1

metadata:
  name: labeling-elb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer
  selector:
    app: labeling-app
  ports:
    - name: http
      port: 32332
      targetPort: 32332
