name: AWS Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Get Private Key
      run: echo "${{ secrets.EC2_DEV_PRIVATE_KEY }}" > ec2_dev_private_key
    
    - run: chmod 600 ec2_dev_private_key
    
    - name: Run rolling update on remote environment
      run: ssh -i ec2_dev_private_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_DEV_HOST_NAME }} kubectl rollout restart deployment helmet-app-deployment
